export { default as Home} from './Home'
export { default as ArtistInfo} from './ArtistInfo'
export { default as Discography} from './Discography'
export { default as Shop} from './Shop'
export { default as NotFound} from './NotFound'