export { default as Home} from './Home'
export { default as Artist} from './Artist'
export { default as Discography} from './Discography'
export { default as Shop} from './Shop'
export { default as NotFound} from './NotFound'